{{ range tuple "1" "2" "3" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $.Chart.Name }}-server-{{ . }}
spec:
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-clickhouse-{{ . }}
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clickhouse-server-data
  local:
    path: /mnt/localstorage/clickhouse-server-data
{{ end }}
