---
apiVersion: batch/v1
kind: Job
metadata:
  name: migration
  annotations:
    "helm.sh/hook": post-install,pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  activeDeadlineSeconds: 600
  template:
    spec:
      containers:
        - name: migration
          command: ['/bin/sh', '-c', 'python manage.py migrate']
          image: {{ .Values.global.image_name }}
          env:
{{- include "app_envs" . | indent 12 }}
          name: migration
      restartPolicy: Never
      imagePullSecrets:
        - name: registrysecret
  backoffLimit: 2



